### ISSUE TITLE
Deleting data watches crashes Spectrum Analyser

### ISSUE THREAD

**Issue by simonowen** [TheGoodDoktor/8BitAnalysers#30]
Reproduction steps:
- find any data location in memory
- right-click on data and select _Add Watch_
- on the Debugger tab select _Watches_
- right-click on the watch entry and select _Delete Watch_
- the application terminates due to an access violation (as seen in Windows Event Viewer)

Tested with current GitHub code (commit 2bc35c89).

**Comment by Colourclash** [comment]
I fixed this in commit e5282f6. I did notice it's possible to add the same watch multiple times which can lead to the context menu displaying Delete Watch multiple times. 

![image](https://github.com/TheGoodDoktor/8BitAnalysers/assets/883891/cd8331c3-299c-4107-92a2-e1debdf9f417)

@TheGoodDoktor Do you think it should use a std::set instead of a std::vector?
